### ISSUE TITLE
Can't compile sample extension.proto

### ISSUE THREAD

**Issue by hkrutzer** [tony612/protobuf-elixir#103]
Input file:
```proto
syntax = "proto2";

package ext;

// -I src is needed, see Makefile
import "elixirpb.proto";

option (elixirpb.file).module_prefix = "Protobuf.Protoc.ExtTest";

message Foo {
  optional string a = 1;
}
```

When I try to run `protoc -I . --elixir_out=gen_descriptors=true,plugins=grpc:./out extension.proto`, I get:

```
** (SyntaxError) nofile:2: unexpected token: "" (column 1, code point U+0017)
    (elixir) lib/code.ex:553: Code.format_string!/2
    (protobuf) lib/protobuf/protoc/generator.ex:64: Protobuf.Protoc.Generator.format_code/1
    (protobuf) lib/protobuf/protoc/generator.ex:11: Protobuf.Protoc.Generator.generate/2
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (protobuf) lib/protobuf/protoc/cli.ex:42: Protobuf.Protoc.CLI.main/1
    (elixir) lib/kernel/cli.ex:121: anonymous fn/3 in Kernel.CLI.exec_fun/2
--elixir_out: protoc-gen-elixir: Plugin failed with status code 1.
```

Versions:
```
> elixir --version
Erlang/OTP 22 [erts-10.4.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 20)

> protoc-gen-elixir --version
0.7.1
```

**Comment by tony612** [comment]
To use the new extension, you have to use the latest protoc-gen-elixir. Note there's a bug here https://github.com/tony612/protobuf-elixir/issues/88

**Comment by hkrutzer** [comment]
I am using 0.7.1

**Comment by tony612** [comment]
The elixirpb.proto you used is on master. If you want to use 0.7.1, you should use the old proto: https://github.com/tony612/protobuf-elixir/tree/v0.7.1

**Comment by hkrutzer** [comment]
That worked, cheers. New release would be appreciated.
