### ISSUE TITLE
module_prefix custom option giving odd errors

### ISSUE THREAD

**Issue by ryanwinchester** [tony612/protobuf-elixir#133]
I have tried with `v0.7.1`, `v0.8.0-beta.1`, and `master`

## Files

`./protobuf/elixirpb.proto`
```proto
// Put this file to elixirpb.proto under PROTO_PATH. See `protoc -h` for `--proto_path` option.
// Then import it
// ````proto
// import "elixirpb.proto";
// ````
//
// 1047 is allocated to this project by Protobuf
// https://github.com/protocolbuffers/protobuf/blob/master/docs/options.md

syntax = "proto2";

package elixirpb;

import "google/protobuf/descriptor.proto";

// File level options
//
// For example,
// option (elixirpb.file).module_prefix = "Foo";
message FileOptions {
  // Specify a module prefix. This will override package name.
  // For example, the package is "hello" and a message is "Request", the message
  // will be "Hello.Request". But with module_prefix "Foo", the message will be
  // "Foo.Request"
  optional string module_prefix = 1;
}

extend google.protobuf.FileOptions {
  optional FileOptions file = 1047;
}
```

`./protobuf/foo/foobar.proto`
```proto
syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "protobuf/elixirpb.proto";

package foobar;

option (elixirpb.file).module_prefix = "Foo";

// ...
```

```bash
protoc --proto_path=./ \
       --elixir_out=gen_descriptors=true,plugins=grpc:./lib/ \
       protobuf/**/*.proto
```

## Results

For every character I add to the module prefix, **_the unicode point goes up by one_**. 😅

### 1

```proto
option (elixirpb.file).module_prefix = "Foo";
```

```bash
** (SyntaxError) nofile:2: unexpected token: "" (column 1, code point U+0003)
```

### 2

```proto
option (elixirpb.file).module_prefix = "Fooo";
```

```bash
** (SyntaxError) nofile:2: unexpected token: "" (column 1, code point U+0004)
```

### 3

```proto
option (elixirpb.file).module_prefix = "Foooo";
```

```bash
** (SyntaxError) nofile:2: unexpected token: "" (column 1, code point U+0005)
```

### 4

```proto
option (elixirpb.file).module_prefix = "Fooo_ooo_ooo";
```

```bash
** (SyntaxError) nofile:2: unexpected token: "
                                              " (column 1, code point U+000C)
```

### Full error message

```bash
** (SyntaxError) nofile:2: unexpected token: "" (column 1, code point U+0005)
    (elixir 1.10.3) lib/code.ex:654: Code.format_string!/2
    (protobuf 0.7.1) lib/protobuf/protoc/generator.ex:64: Protobuf.Protoc.Generator.format_code/1
    (protobuf 0.7.1) lib/protobuf/protoc/generator.ex:11: Protobuf.Protoc.Generator.generate/2
    (elixir 1.10.3) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (protobuf 0.7.1) lib/protobuf/protoc/cli.ex:42: Protobuf.Protoc.CLI.main/1
    (elixir 1.10.3) lib/kernel/cli.ex:124: anonymous fn/3 in Kernel.CLI.exec_fun/2
--elixir_out: protoc-gen-elixir: Plugin failed with status code 1.
```

**Comment by hkrutzer** [comment]
I had [the same error](https://github.com/tony612/protobuf-elixir/issues/103) but for me `master` did work.

**Comment by ryanwinchester** [comment]
> I had [the same error](https://github.com/tony612/protobuf-elixir/issues/103) but for me `master` did work.

@hkrutzer Do you have an example of working `elixirpb.proto` and file that imports it? Because no matter what I do, I can't get it to work.

**Comment by hkrutzer** [comment]
I used the one from the repo, and  `protoc -I proto/ --elixir_out=plugins=grpc:./app/lib/proto proto/**.proto` with `mix escript.install github tony612/protobuf-elixir`

**Comment by ryanwinchester** [comment]
### Example repo

Here is an example brand new project with two proto files in `./protobuf`:

https://github.com/ryanwinchester/elixir-protobuf-module-prefix-no-worky

The files are the elixirpb from master, and the second one is the example usage of it from the readme on master.

### Compiling protos

To compile them use `./compile-protos`

which is really just:

```bash
protoc -I protobuf/ --elixir_out=plugins=grpc:./lib/protobuf_test protobuf/**.proto
```

### Result

```
$ ./compile-protos
** (SyntaxError) nofile:2: unexpected token: "" (column 1, code point U+0007)
    (elixir 1.10.3) lib/code.ex:654: Code.format_string!/2
    (protobuf 0.7.1) lib/protobuf/protoc/generator.ex:64: Protobuf.Protoc.Generator.format_code/1
    (protobuf 0.7.1) lib/protobuf/protoc/generator.ex:11: Protobuf.Protoc.Generator.generate/2
    (elixir 1.10.3) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.10.3) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (protobuf 0.7.1) lib/protobuf/protoc/cli.ex:42: Protobuf.Protoc.CLI.main/1
    (elixir 1.10.3) lib/kernel/cli.ex:124: anonymous fn/3 in Kernel.CLI.exec_fun/2
--elixir_out: protoc-gen-elixir: Plugin failed with status code 1.
```

**Comment by ryanwinchester** [comment]
I figured it out. 🤦‍♂️

It's an issue with the escript `mix escript.install github tony612/protobuf-elixir` + using `asdf`

**Comment by hkrutzer** [comment]
`asdf reshim` :D
