### ISSUE TITLE
Function clause exception when decoding garbage binaries

### ISSUE THREAD

**Issue by haljin** [tony612/protobuf-elixir#71]
Hi, 

When I try to decode an obviously wrong binary as a protobuf struct I get a function clause exception, e.g.:

```
iex(2)> Protobuf.Decoder.decode(<<1,1,1>>, SomeProtoStruct)
** (FunctionClauseError) no function clause matching in Protobuf.Decoder.raw_decode_value/3    
    
    The following arguments were given to Protobuf.Decoder.raw_decode_value/3:
    
        # 1
        1
    
        # 2
        <<1, 1>>
    
        # 3
        [1, 0]
    
    Attempted function clauses (showing 4 out of 4):
    
        def raw_decode_value(0, <<bin::bitstring()>>, result)
        def raw_decode_value(2, <<bin::bitstring()>>, result)
        def raw_decode_value(5, <<n::integer()-size(32), rest::bitstring()>>, result)
        def raw_decode_value(1, <<n::integer()-size(64), rest::bitstring()>>, result)
    
    (protobuf) lib/protobuf/decoder.ex:283: Protobuf.Decoder.raw_decode_value/3
    (protobuf) lib/protobuf/decoder.ex:13: Protobuf.Decoder.decode/2
```

The thing is, I'd like to be able to distinguish these errors from other function clause exceptions that might happen in the same process. Currently the only way is to wrap the decode like this:

```
 defp decode(msg) do
    SomeProtoStruct.decode(msg)
  catch
    _, _ ->
      raise Protobuf.DecodeError
  end
```

Could the auto-generated decode function not do this? I'm willing to make a PR for this if you agree.

**Comment by tony612** [comment]
I think we can add error handling in `Protobuf.Decoder.decode` and reraise the error using Protobuf.DecodeError. Please send a PR if you want to.
